###getting all users

GET http://localhost:3000/users
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImZpcnN0X25hbWUiOiJHQiIsImxhc3RfbmFtZSI6IlRlc3QgVXNlciIsImVtYWlsIjoibkBnLmNtIiwicGhvbmVfbnVtYmVyIjoiIiwibnVtX2lzX3ZlcmlmaWVkIjpmYWxzZSwiZW1haWxfaXNfdmVyaWZpZWQiOmZhbHNlLCJwYXNzd29yZCI6Imswbi4xMiwzPjw0NSc2ZmdoOCIsImRvYiI6IjIwMjMtMTItMDFUMjM6MDA6MDAuMDAwWiIsImlzX3ZlcmlmaWVkIjpmYWxzZSwibG95YWx0eV9wb2ludHMiOjAsInJlZmVyYWxfY29kZSI6IjhJQ0kyWiIsImFkZHJlc3MiOnsiY291bnRyeSI6IkNhbWVyb29uIn0sInNldHRpbmdzIjp7Im5vdGlmaWNhdGlvbl90eXBlcyI6W10sInRoZW1lIjoibGlnaHQifSwicGF5bWVudF9tZXRob2RzIjpbXSwiX2lkIjoiNjY2NDJjZjJhMGU3ZDA5ZDI1ZWQ5NDJmIiwicGluIjozNjgyMX0sImlhdCI6MTcxNzg0MTEzOCwiZXhwIjoxNzE3ODg0MzM4fQ.o3wQnTWPSiPkh0Kd4sRgmSwD6WHSWXi9F9vlw9ekQgg
### finding one user

GET http://localhost:3000/users/66642cc0a0e7d09d25ed9425
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImZpcnN0X25hbWUiOiJHQiIsImxhc3RfbmFtZSI6IlRlc3QgVXNlciIsImVtYWlsIjoibkBnLmMiLCJwaG9uZV9udW1iZXIiOiIiLCJudW1faXNfdmVyaWZpZWQiOmZhbHNlLCJlbWFpbF9pc192ZXJpZmllZCI6ZmFsc2UsInBhc3N3b3JkIjoiazBuLjEyLDM-PDQ1JzZmZ2g4IiwiZG9iIjoiMjAyMy0xMi0wMVQyMzowMDowMC4wMDBaIiwiaXNfdmVyaWZpZWQiOmZhbHNlLCJsb3lhbHR5X3BvaW50cyI6MCwiYWRkcmVzcyI6eyJjb3VudHJ5IjoiQ2FtZXJvb24ifSwic2V0dGluZ3MiOnsibm90aWZpY2F0aW9uX3R5cGVzIjpbXSwidGhlbWUiOiJsaWdodCJ9LCJwYXltZW50X21ldGhvZHMiOltdLCJfaWQiOiI2NjY0MjMxNDQzZDE5OGJhYjA2NmM0ZjciLCJwaW4iOjEwMTQ4fSwiaWF0IjoxNzE3ODM4NjEyLCJleHAiOjE3MTc4ODE4MTJ9.E7tVhgSOg21aeRABJcBYjtoL5kc9e8DKkddeZCJ9A64


###creating new user
POST http://localhost:3000/register
Content-Type: application/json

{
        "first_name":"GB",
        "last_name":"Test User",
        "phone_number":"23456789",
        "password":"k0n.12,3><45'6fgh8",
        "dob":"2023-12-2"
}

### login user

POST http://localhost:3000/login
Content-Type: application/json

{
    "credential":"n@g.c",
    "password":"k0n.12,3><45'6fgh8"
}

### Delete user
DELETE http://localhost:3000/users/6664211211c4a713bc21308d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImZpcnN0X25hbWUiOiJHQiIsImxhc3RfbmFtZSI6IlRlc3QgVXNlciIsImVtYWlsIjoibkBnLmMiLCJwaG9uZV9udW1iZXIiOiIiLCJudW1faXNfdmVyaWZpZWQiOmZhbHNlLCJlbWFpbF9pc192ZXJpZmllZCI6ZmFsc2UsInBhc3N3b3JkIjoiazBuLjEyLDM-PDQ1JzZmZ2g4IiwiZG9iIjoiMjAyMy0xMi0wMVQyMzowMDowMC4wMDBaIiwiaXNfdmVyaWZpZWQiOmZhbHNlLCJsb3lhbHR5X3BvaW50cyI6MCwiYWRkcmVzcyI6eyJjb3VudHJ5IjoiQ2FtZXJvb24ifSwic2V0dGluZ3MiOnsibm90aWZpY2F0aW9uX3R5cGVzIjpbXSwidGhlbWUiOiJsaWdodCJ9LCJwYXltZW50X21ldGhvZHMiOltdLCJfaWQiOiI2NjY0MjMxNDQzZDE5OGJhYjA2NmM0ZjciLCJwaW4iOjEwMTQ4fSwiaWF0IjoxNzE3ODM4NjEyLCJleHAiOjE3MTc4ODE4MTJ9.E7tVhgSOg21aeRABJcBYjtoL5kc9e8DKkddeZCJ9A64

### week 2

### get new user pin
PATCH http://localhost:3000/users/66642cc0a0e7d09d25ed9425/updatePin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImZpcnN0X25hbWUiOiJHQiIsImxhc3RfbmFtZSI6IlRlc3QgVXNlciIsImVtYWlsIjoibkBnLmNtIiwicGhvbmVfbnVtYmVyIjoiIiwibnVtX2lzX3ZlcmlmaWVkIjpmYWxzZSwiZW1haWxfaXNfdmVyaWZpZWQiOmZhbHNlLCJwYXNzd29yZCI6Imswbi4xMiwzPjw0NSc2ZmdoOCIsImRvYiI6IjIwMjMtMTItMDFUMjM6MDA6MDAuMDAwWiIsImlzX3ZlcmlmaWVkIjpmYWxzZSwibG95YWx0eV9wb2ludHMiOjAsInJlZmVyYWxfY29kZSI6IjhJQ0kyWiIsImFkZHJlc3MiOnsiY291bnRyeSI6IkNhbWVyb29uIn0sInNldHRpbmdzIjp7Im5vdGlmaWNhdGlvbl90eXBlcyI6W10sInRoZW1lIjoibGlnaHQifSwicGF5bWVudF9tZXRob2RzIjpbXSwiX2lkIjoiNjY2NDJjZjJhMGU3ZDA5ZDI1ZWQ5NDJmIiwicGluIjozNjgyMX0sImlhdCI6MTcxNzg0MTEzOCwiZXhwIjoxNzE3ODg0MzM4fQ.o3wQnTWPSiPkh0Kd4sRgmSwD6WHSWXi9F9vlw9ekQgg


Content-Type: application/json

{
     
}

####

### get user pin 
GET http://localhost:3000/users/66642cc0a0e7d09d25ed9425/pin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImZpcnN0X25hbWUiOiJHQiIsImxhc3RfbmFtZSI6IlRlc3QgVXNlciIsImVtYWlsIjoibkBnLmNtIiwicGhvbmVfbnVtYmVyIjoiIiwibnVtX2lzX3ZlcmlmaWVkIjpmYWxzZSwiZW1haWxfaXNfdmVyaWZpZWQiOmZhbHNlLCJwYXNzd29yZCI6Imswbi4xMiwzPjw0NSc2ZmdoOCIsImRvYiI6IjIwMjMtMTItMDFUMjM6MDA6MDAuMDAwWiIsImlzX3ZlcmlmaWVkIjpmYWxzZSwibG95YWx0eV9wb2ludHMiOjAsInJlZmVyYWxfY29kZSI6IjhJQ0kyWiIsImFkZHJlc3MiOnsiY291bnRyeSI6IkNhbWVyb29uIn0sInNldHRpbmdzIjp7Im5vdGlmaWNhdGlvbl90eXBlcyI6W10sInRoZW1lIjoibGlnaHQifSwicGF5bWVudF9tZXRob2RzIjpbXSwiX2lkIjoiNjY2NDJjZjJhMGU3ZDA5ZDI1ZWQ5NDJmIiwicGluIjozNjgyMX0sImlhdCI6MTcxNzg0MTEzOCwiZXhwIjoxNzE3ODg0MzM4fQ.o3wQnTWPSiPkh0Kd4sRgmSwD6WHSWXi9F9vlw9ekQgg
Content-Type: application/json

{
     
}

### add new delivery address
POST http://localhost:3000/users/66642cc0a0e7d09d25ed9425/deliveryAddress
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImZpcnN0X25hbWUiOiJHQiIsImxhc3RfbmFtZSI6IlRlc3QgVXNlciIsImVtYWlsIjoibkBnLmNtIiwicGhvbmVfbnVtYmVyIjoiIiwibnVtX2lzX3ZlcmlmaWVkIjpmYWxzZSwiZW1haWxfaXNfdmVyaWZpZWQiOmZhbHNlLCJwYXNzd29yZCI6Imswbi4xMiwzPjw0NSc2ZmdoOCIsImRvYiI6IjIwMjMtMTItMDFUMjM6MDA6MDAuMDAwWiIsImlzX3ZlcmlmaWVkIjpmYWxzZSwibG95YWx0eV9wb2ludHMiOjAsInJlZmVyYWxfY29kZSI6IjhJQ0kyWiIsImFkZHJlc3MiOnsiY291bnRyeSI6IkNhbWVyb29uIn0sInNldHRpbmdzIjp7Im5vdGlmaWNhdGlvbl90eXBlcyI6W10sInRoZW1lIjoibGlnaHQifSwicGF5bWVudF9tZXRob2RzIjpbXSwiX2lkIjoiNjY2NDJjZjJhMGU3ZDA5ZDI1ZWQ5NDJmIiwicGluIjozNjgyMX0sImlhdCI6MTcxNzg0MTEzOCwiZXhwIjoxNzE3ODg0MzM4fQ.o3wQnTWPSiPkh0Kd4sRgmSwD6WHSWXi9F9vlw9ekQgg
Content-Type: application/json

{
     "street":"xxxxx",
     "city":"California",
     "country":"United states"
}

### get all addresses from a single user


GET http://localhost:3000/users/66642cc0a0e7d09d25ed9425/deliveryAddress
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImZpcnN0X25hbWUiOiJHQiIsImxhc3RfbmFtZSI6IlRlc3QgVXNlciIsImVtYWlsIjoibkBnLmNtIiwicGhvbmVfbnVtYmVyIjoiIiwibnVtX2lzX3ZlcmlmaWVkIjpmYWxzZSwiZW1haWxfaXNfdmVyaWZpZWQiOmZhbHNlLCJwYXNzd29yZCI6Imswbi4xMiwzPjw0NSc2ZmdoOCIsImRvYiI6IjIwMjMtMTItMDFUMjM6MDA6MDAuMDAwWiIsImlzX3ZlcmlmaWVkIjpmYWxzZSwibG95YWx0eV9wb2ludHMiOjAsInJlZmVyYWxfY29kZSI6IjhJQ0kyWiIsImFkZHJlc3MiOnsiY291bnRyeSI6IkNhbWVyb29uIn0sInNldHRpbmdzIjp7Im5vdGlmaWNhdGlvbl90eXBlcyI6W10sInRoZW1lIjoibGlnaHQifSwicGF5bWVudF9tZXRob2RzIjpbXSwiX2lkIjoiNjY2NDJjZjJhMGU3ZDA5ZDI1ZWQ5NDJmIiwicGluIjozNjgyMX0sImlhdCI6MTcxNzg0MTEzOCwiZXhwIjoxNzE3ODg0MzM4fQ.o3wQnTWPSiPkh0Kd4sRgmSwD6WHSWXi9F9vlw9ekQgg
Content-Type: application/json

{
     
}

### get one particular delivery address from a user
GET http://localhost:3000/users/66642cc0a0e7d09d25ed9425/deliveryAddress/666446b5b238108b5bdaceaf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImZpcnN0X25hbWUiOiJHQiIsImxhc3RfbmFtZSI6IlRlc3QgVXNlciIsImVtYWlsIjoibkBnLmNtIiwicGhvbmVfbnVtYmVyIjoiIiwibnVtX2lzX3ZlcmlmaWVkIjpmYWxzZSwiZW1haWxfaXNfdmVyaWZpZWQiOmZhbHNlLCJwYXNzd29yZCI6Imswbi4xMiwzPjw0NSc2ZmdoOCIsImRvYiI6IjIwMjMtMTItMDFUMjM6MDA6MDAuMDAwWiIsImlzX3ZlcmlmaWVkIjpmYWxzZSwibG95YWx0eV9wb2ludHMiOjAsInJlZmVyYWxfY29kZSI6IjhJQ0kyWiIsImFkZHJlc3MiOnsiY291bnRyeSI6IkNhbWVyb29uIn0sInNldHRpbmdzIjp7Im5vdGlmaWNhdGlvbl90eXBlcyI6W10sInRoZW1lIjoibGlnaHQifSwicGF5bWVudF9tZXRob2RzIjpbXSwiX2lkIjoiNjY2NDJjZjJhMGU3ZDA5ZDI1ZWQ5NDJmIiwicGluIjozNjgyMX0sImlhdCI6MTcxNzg0MTEzOCwiZXhwIjoxNzE3ODg0MzM4fQ.o3wQnTWPSiPkh0Kd4sRgmSwD6WHSWXi9F9vlw9ekQgg
Content-Type: application/json

{
     
}

### update existing delivery address
PATCH http://localhost:3000/users/66642cc0a0e7d09d25ed9425/deliveryAddress/666449795b5ccf4ee3b1e673
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImZpcnN0X25hbWUiOiJHQiIsImxhc3RfbmFtZSI6IlRlc3QgVXNlciIsImVtYWlsIjoibkBnLmNtIiwicGhvbmVfbnVtYmVyIjoiIiwibnVtX2lzX3ZlcmlmaWVkIjpmYWxzZSwiZW1haWxfaXNfdmVyaWZpZWQiOmZhbHNlLCJwYXNzd29yZCI6Imswbi4xMiwzPjw0NSc2ZmdoOCIsImRvYiI6IjIwMjMtMTItMDFUMjM6MDA6MDAuMDAwWiIsImlzX3ZlcmlmaWVkIjpmYWxzZSwibG95YWx0eV9wb2ludHMiOjAsInJlZmVyYWxfY29kZSI6IjhJQ0kyWiIsImFkZHJlc3MiOnsiY291bnRyeSI6IkNhbWVyb29uIn0sInNldHRpbmdzIjp7Im5vdGlmaWNhdGlvbl90eXBlcyI6W10sInRoZW1lIjoibGlnaHQifSwicGF5bWVudF9tZXRob2RzIjpbXSwiX2lkIjoiNjY2NDJjZjJhMGU3ZDA5ZDI1ZWQ5NDJmIiwicGluIjozNjgyMX0sImlhdCI6MTcxNzg0MTEzOCwiZXhwIjoxNzE3ODg0MzM4fQ.o3wQnTWPSiPkh0Kd4sRgmSwD6WHSWXi9F9vlw9ekQgg
Content-Type: application/json

{
     "street":"Mile 29",
     "city":"Muyuka",
     "country":""
}

### delete individual address

DELETE http://localhost:3000/users/66642cc0a0e7d09d25ed9425/deliveryAddress/66644e4b155c982ea7516d80
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImZpcnN0X25hbWUiOiJHQiIsImxhc3RfbmFtZSI6IlRlc3QgVXNlciIsImVtYWlsIjoibkBnLmNtIiwicGhvbmVfbnVtYmVyIjoiIiwibnVtX2lzX3ZlcmlmaWVkIjpmYWxzZSwiZW1haWxfaXNfdmVyaWZpZWQiOmZhbHNlLCJwYXNzd29yZCI6Imswbi4xMiwzPjw0NSc2ZmdoOCIsImRvYiI6IjIwMjMtMTItMDFUMjM6MDA6MDAuMDAwWiIsImlzX3ZlcmlmaWVkIjpmYWxzZSwibG95YWx0eV9wb2ludHMiOjAsInJlZmVyYWxfY29kZSI6IjhJQ0kyWiIsImFkZHJlc3MiOnsiY291bnRyeSI6IkNhbWVyb29uIn0sInNldHRpbmdzIjp7Im5vdGlmaWNhdGlvbl90eXBlcyI6W10sInRoZW1lIjoibGlnaHQifSwicGF5bWVudF9tZXRob2RzIjpbXSwiX2lkIjoiNjY2NDJjZjJhMGU3ZDA5ZDI1ZWQ5NDJmIiwicGluIjozNjgyMX0sImlhdCI6MTcxNzg0MTEzOCwiZXhwIjoxNzE3ODg0MzM4fQ.o3wQnTWPSiPkh0Kd4sRgmSwD6WHSWXi9F9vlw9ekQgg
Content-Type: application/json

{
     
}

###
