const translations = {
    en: {
        "welcome": "Welcome",
        "Basket Created": "Basket Created",
        "Your basket has been created successfully": "Your basket has been created successfully",
        "A new order has been created": "A new order has been created",
        "✅ Order Received": "✅ Order Received",
        "Thank you for placing your order with GlobalBuy24. We’ve received your request and are now verifying the product details. We’ll notify you once we place the order.": "Thank you for placing your order with GlobalBuy24. We’ve received your request and are now verifying the product details. We’ll notify you once we place the order.",
        "🔍 Order Under Review": "🔍 Order Under Review",
        "Our team is reviewing your product link(s) to confirm availability, price, shipping, and size/variant information. We’ll send you a quote shortly.": "Our team is reviewing your product link(s) to confirm availability, price, shipping, and size/variant information. We’ll send you a quote shortly.",
        "💳 Payment Confirmed": "💳 Payment Confirmed",
        "We’ve received your payment of {amount}XAF successfully. We are now placing your order with the seller. You’ll be notified once the item arrives at our hub in Berlin.": "We’ve received your payment of {amount}XAF successfully. We are now placing your order with the seller. You’ll be notified once the item arrives at our hub in Berlin.",
        "Payment Failed": "Payment Failed",
        "Your payment of {amount}XAF has failed": "Your payment of {amount}XAF has failed",
        "Payment Expired": "Payment Expired",
        "Your payment of {amount}XAF has expired": "Your payment of {amount}XAF has expired",
        "Welcome to GlobalBuy": "Welcome to GlobalBuy",
        "Thank you for registering with GlobalBuy. We're excited to have you on board!": "Thank you for registering with GlobalBuy. We're excited to have you on board!",
        "GB welcomes you, {first_name} {last_name}. Enjoy your ride with us.": "GB welcomes you, {first_name} {last_name}. Enjoy your ride with us.",
        "Your verification code is: {temp_code} . It is valid for 5 minutes.Do not share this code with anyone. Need Help? Visit the help centre on the app or globalbuy24.com": "Your verification code is: {temp_code} . It is valid for 5 minutes.Do not share this code with anyone. Need Help? Visit the help centre on the app or globalbuy24.com",
        "Verification code": "Verification code",
        "Your verification code is: {otp}": "Your verification code is: {otp}",
        "Welcome to GB!": "Welcome to GB!",
        "Hello and welcome 👋,": "Hello and welcome 👋,",
        "We’re excited to have you on board. With GlobalBuy24, you can easily <span class=\"highlight\">shop from global online stores</span> and get your purchases delivered to you in Cameroon — reliably, affordably, and hassle-free.": "We’re excited to have you on board. With GlobalBuy24, you can easily <span class=\"highlight\">shop from global online stores</span> and get your purchases delivered to you in Cameroon — reliably, affordably, and hassle-free.",
        "Here’s what you can do with the GlobalBuy24 app:": "Here’s what you can do with the GlobalBuy24 app:",
        "🛒 Simply add product links from any online store worldwide (e.g., Amazon, Temu, eBay, Fashion Nova, SHEIN, and more)": "🛒 Simply add product links from any online store worldwide (e.g., Amazon, Temu, eBay, Fashion Nova, SHEIN, and more)",
        "📦 Request quotes and confirm orders": "📦 Request quotes and confirm orders",
        "🚀 Track shipping and delivery straight to Cameroon": "🚀 Track shipping and delivery straight to Cameroon",
        "We can’t wait to help you shop the world.": "We can’t wait to help you shop the world.",
        "Happy shopping!": "Happy shopping!",
        "The GlobalBuy Team": "The GlobalBuy Team",
        "2025 GlobalBuy. All rights reserved.": "2025 GlobalBuy. All rights reserved.",
        "Your OTP Code": "Your OTP Code",
        "Hello,": "Hello,",
        "To complete your GlobalBuy sign-up, please enter the following verification code in the app:": "To complete your GlobalBuy sign-up, please enter the following verification code in the app:",
        "This OTP is valid for <strong>5 minutes</strong>. Please do not share this code with anyone.": "This OTP is valid for <strong>5 minutes</strong>. Please do not share this code with anyone.",
        "If you didn't request this code, please ignore this email.": "If you didn't request this code, please ignore this email.",
        "Thank you for using our service!": "Thank you for using our service!",
        "Order Status Update": "Order Status Update",
        "Your order {order_num} status has been updated to {status}.": "Your order {order_num} status has been updated to {status}.",
        "Order Progress Update": "Order Progress Update",
        "Order Progress Update": "Order Progress Update",
        "We have received your order #{order_num} and it is being processed.": "We have received your order #{order_num} and it is being processed.",
        "Your order #{order_num} has been received at our warehouse.": "Your order #{order_num} has been received at our warehouse.",
        "Your order #{order_num} has been shipped.": "Your order #{order_num} has been shipped.",
        "Your order #{order_num} has arrived at the destination country.": "Your order #{order_num} has arrived at the destination country.",
        "Your order #{order_num} is ready for pickup.": "Your order #{order_num} is ready for pickup."
    },
    fr: {
        "welcome": "Bienvenue",
        "Order Progress Update": "Mise à jour de la progression de la commande",
        "Your order {order_num} progress for {progress_item} has been updated to {status}.": "La progression de votre commande {order_num} pour {progress_item} a été mise à jour à {status}.",
        "Order Status Update": "Mise à jour du statut de la commande",
        "Your order {order_num} status has been updated to {status}.": "Le statut de votre commande {order_num} a été mis à jour à {status}.",
        "We have received your order #{order_num} and it is being processed.": "Nous avons reçu votre commande #{order_num} et elle est en cours de traitement.",
        "Your order #{order_num} has been received at our entrepôt.": "Votre commande #{order_num} a été reçue à notre entrepôt.",
        "Your order #{order_num} has been shipped.": "Votre commande #{order_num} a été expédiée.",
        "Your order #{order_num} has arrived at the destination country.": "Votre commande #{order_num} est arrivée dans le pays de destination.",
        "Your order #{order_num} is ready for pickup.": "Votre commande #{order_num} est prête à être récupérée.",
        "Basket Created": "Panier créé",
        "Your OTP Code": "Votre code OTP",
        "Hello,": "Bonjour,",
        "To complete your GlobalBuy24 sign-up, please enter the following verification code in the app:": "Pour finaliser votre inscription à GlobalBuy24, veuillez saisir le code de vérification suivant dans l'application :",
        "This OTP is valid for <strong>5 minutes</strong>. Please do not share this code with anyone.": "Cet OTP est valable <strong>5 minutes</strong>. Veuillez ne pas partager ce code avec qui que ce soit.",
        "If you didn't request this code, please ignore this email.": "Si vous n'avez pas demandé ce code, veuillez ignorer cet e-mail.",
        "Thank you for using our service!": "Merci d'utiliser notre service !",
        "Your basket has been created successfully": "Votre panier a été créé avec succès",
        "A new order has been created": "Une nouvelle commande a été créée",
        "✅ Order Received": "✅ Commande Reçue",
        "Thank you for placing your order with GlobalBuy24. We’ve received your request and are now verifying the product details. We’ll notify you once we place the order.": "Merci d'avoir passé votre commande avec GlobalBuy24. Nous avons reçu votre demande et vérifions maintenant les détails du produit. Nous vous informerons une fois que nous aurons passé la commande.",
        "🔍 Order Under Review": "🔍 Commande en cours d'examen",
        "Our team is reviewing your product link(s) to confirm availability, price, shipping, and size/variant information. We’ll send you a quote shortly.": "Notre équipe examine votre ou vos liens de produits pour confirmer la disponibilité, le prix, l'expédition et les informations de taille/variante. Nous vous enverrons un devis sous peu.",
        "💳 Payment Confirmed": "💳 Paiement Confirmé",
        "We’ve received your payment of {amount}XAF successfully. We are now placing your order with the seller. You’ll be notified once the item arrives at our hub in Berlin.": "Nous avons reçu votre paiement de {amount}XAF avec succès. Nous passons maintenant votre commande auprès du vendeur. Vous serez informé dès que l'article arrivera à notre entrepôt à Berlin.",
        "Payment Failed": "Paiement échoué",
        "Your payment of {amount}XAF has failed": "Votre paiement de {amount}XAF a échoué",
        "Payment Expired": "Paiement expiré",
        "Your payment of {amount}XAF a expired": "Votre paiement de {amount}XAF a expiré",
        "Welcome to GlobalBuy": "Bienvenue chez GlobalBuy",
        "Thank you for registering with GlobalBuy. We're excited to have you on board!": "Merci de vous être inscrit sur GlobalBuy. Nous sommes ravis de vous compter parmi nous !",
        "GB welcomes you, {first_name} {last_name}. Enjoy your ride with us.": "GB vous souhaite la bienvenue, {first_name} {last_name}. Profitez de votre expérience avec nous.",
        "Your verification code is: {temp_code} . It is valid for 5 minutes.Do not share this code with anyone. Need Help? Visit the help centre on the app or globalbuy24.com": "Votre code de vérification est : {temp_code} . Il est valable 5 minutes. Ne partagez ce code avec personne. Besoin d'aide ? Visitez le centre d'aide sur l'application ou globalbuy24.com",
        "Verification code": "Code de vérification",
        "Your verification code is: {otp}": "Votre code de vérification est : {otp}",
        "Welcome to GB!": "Bienvenue chez GB !",
        "Hello and welcome 👋,": "Bonjour et bienvenue 👋,",
        "We’re excited to have you on board. With GlobalBuy, you can easily <span class=\"highlight\">shop from global online stores</span> and get your purchases delivered to you in Cameroon — reliably, affordably, and hassle-free.": "Nous sommes ravis de vous compter parmi nous. Avec GlobalBuy, vous pouvez facilement <span class=\"highlight\">acheter dans des magasins en ligne mondiaux</span> et faire livrer vos achats au Cameroun — de manière fiable, abordable et sans tracas.",
        "Here’s what you can do with the GlobalBuy app:": "Voici ce que vous pouvez faire avec l'application GlobalBuy :",
        "🛒 Simply add product links from any online store worldwide (e.g., Amazon, Temu, eBay, Fashion Nova, SHEIN, and more)": "🛒 Ajoutez simplement des liens de produits de n'importe quel magasin en ligne mondial (par exemple, Amazon, Temu, eBay, Fashion Nova, SHEIN, et plus encore)",
        "📦 Request quotes and confirm orders": "📦 Demandez des devis et confirmez les commandes",
        "🚀 Track shipping and delivery straight to Cameroon": "🚀 Suivez l'expédition et la livraison directement au Cameroun",
        "We can’t wait to help you shop the world.": "Nous avons hâte de vous aider à acheter dans le monde entier.",
        "Happy shopping!": "Bon shopping !",
        "The GlobalBuy Team": "L'équipe GlobalBuy",
        "2025 GlobalBuy. All rights reserved.": "2025 GlobalBuy. Tous droits réservés.",
        "Order Progress Update": "Mise à jour de la progression de la commande",
    }
};

const translate = (key, lang, replacements = {}) => {
    const language = lang && translations[lang] ? lang : 'en'; // Default to English if language is not supported
    let message = translations[language][key] || translations['en'][key] || key; // Fallback to English, then to key itself

    for (const placeholder in replacements) {
        message = message.replace(`{${placeholder}}`, replacements[placeholder]);
    }
    return message;
};

export default translate;
